### PR TITLE
Add support for overriding typecast

### PR DESCRIPTION
**Pull request by jarlah**
This is what I meant about supporting commas. Its quite weird not to support precision numbers so here is my contribution for how it can be solved :) 👍 

PS! I saw that the dist file was updated, but its quite frustrating having to filter this out when doing other work, so I thought it best to commit the changes to it.

### CODE REVIEW

**Comment by scotthovestadt** [comment]
I'm not why the "transform" function parameter wouldn't fix this -- doesn't it allow you raw access to the variable pre-typecast?

I can see value in having a number-specific parameter to convert commas to precision.

**Comment by jarlah** [comment]
You cant use transform because transform is done after typecast. And we dont need to actually introduce a typecast method. I am in a nutshell without the extra code proposing simply to support decimal Numbers :)

**Comment by scotthovestadt** [comment]
There is a general transform (NOT numberTransform) that happens before typecast.
```
function typecast(value, originalValue, properties) {
  // Allow transform to manipulate raw properties.
  if(properties.transform) {
    value = properties.transform.call(this[_privateKey]._root, value, originalValue, properties);
  }

  // Property types are always normalized as lowercase strings despite shorthand definitions being available.
  switch(properties.type) {
```

I think that removes the need for the `typecast` property.

However, I am OK with adding a special property to numbers that allows "," to be treated as ".".

**Comment by jarlah** [comment]
Omg. So silly. Its like reading a book by bobby fischer where he constantly nags about looking at the whole board and you still cannot see the two moves for check mate. 

In other words the generic transform passed me by. Ill Try it out. But yes it would be nice with automatic support for comma precision. And as you havent used comma for US way of signaling thousands it might work until someone also wants decimal numbers but not with comma ... :/ strolls by

We can let the PR be open for just a little while longer while i Try out the generic transform

**Comment by scotthovestadt** [comment]
Yeah, you're probably right. I'll keep parsing commas as the default US behavior but add a parameter to adjust it.

-Scott

**Comment by jarlah** [comment]
Closing this since its not relevant to add support for decimal numbers by default. I can instead make an object describing a decimal number .. for eks const Number = { type: 'Number', transform: () => .... } etc ... so I think we can close this.

**Pull request closed without merging**
