### PR TITLE
Adds support for required property. see issue #15

### PR DESCRIPTION
**Pull request by abpai**

### CODE REVIEW

**Comment by scotthovestadt** [comment]
@abpai Thanks for the merge request.

Can you provide a test for the behavior of a initializing an object without the property, providing the property, and then checking errors? I don't think the implementation will work for that use-case (and it's a pretty basic one).

Something like this:

```
var SO = new SchemaObject({
	name: { type: String, required: true }
});

o = new SO();
o.name = 'hello world';

o.getErrors().length.should.equal(0);
o.isErrors().should.equal(false);
```

**Comment by abpai** [comment]
Oh right. Thanks for your feedback. I'll add support for that. I wasn't totally sure how to handle that since I didn't expect this behavior in the example below:

```
const SchemaObject = require("schema-object")

const SO = new SchemaObject({ must_be_string: String, foo: String })
const o = new SO({ must_be_string: [], foo: 'bar' })
o.must_be_string = 'now is string'
o.foo = 'is ok'

console.log(o) // { must_be_string: 'now is string', foo: 'is ok' }

// still has error related to array provided initially for must_be_string
console.log(o.getErrors())
```

Should we cleaning up errors for values set after the initialization?

**Comment by scotthovestadt** [comment]
@abpai Probably the way it generates errors right now in general - by running the validation and creating an error on set - needs a bit of a refactor. For the feature you want in particular, you don't need to refactor a lot. I think you can just add some logic to `getErrors` that'll go through the schema and add an error to the list dynamically if a required field is empty (instead of doing it on-set).

I'll eventually probably make all errors work that way. It makes more sense.

**Comment by abpai** [comment]
@scotthovestadt I think this fixes both issues?

**Comment by scotthovestadt** [comment]
@abpai Looks good. I need to fix the implementation to work in older versions of NodeJS - I see the tests are failing - but I can take a look at that tomorrow and then merge it in and push it up.

**Comment by abpai** [comment]
@scotthovestadt Fixed older node

**Comment by scotthovestadt** [comment]
@abpai thanks for your PR. i'll get it pushed up into NPM tomorrow.

**Comment by abpai** [comment]
@scotthovestadt Thanks bud for the great lib and fast feedback.

**Comment by scotthovestadt** [comment]
@abpai Sorry for delay publishing. I found a use-case where the error would fail to generate - see commit (test at bottom of diff). https://github.com/scotthovestadt/schema-object/commit/96f0c9f159a4d62d8aca7ef24b5efb81a369965d#diff-38dcab2adf8a7e3431829d8daca050fcR627

Fixed, test added, and published as 4.0.8.

**Pull request merged**
